const $=id=>document.getElementById(id),timeline=$('timeline');
let socket=null,currentSession=null,currentJob=null,token=localStorage.getItem('ans_token')||'';
const authHeaders=()=>token?{'Authorization':'Bearer '+token}:{};
function add(kind,msg){if(timeline.querySelector('.empty'))timeline.innerHTML='';const d=document.createElement('div');const b=document.createElement('b');b.textContent=kind;const s=document.createElement('span');s.textContent=' '+msg;d.append(b,s);timeline.appendChild(d);timeline.scrollTop=timeline.scrollHeight}
function connect(sid){if(socket)socket.close();socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws/'+sid+'?token='+encodeURIComponent(token));socket.onmessage=e=>{const x=JSON.parse(e.data);add(x.kind||'EVENT',x.message||'');if(x.kind==='approval.required'){currentSession=sid;$('approval').classList.remove('hidden');$('approvalText').textContent=x.tool+': '+JSON.stringify(x.args||{})}if(x.kind==='run.completed'){$('runstatus').textContent=(x.status||'completed').toUpperCase();load();loadFiles();loadGit();loadDiff()}}}
async function api(url,opts={}){opts.headers={...(opts.headers||{}),...authHeaders()};const r=await fetch(url,opts);if(r.status===401){token=prompt('Enter ANS auth token');if(token){localStorage.setItem('ans_token',token);opts.headers=authHeaders();return fetch(url,opts)}}return r}
async function load(){try{const h=await fetch('/health');$('health').textContent=h.ok?'● ONLINE':'● OFFLINE';$('health').className='status '+(h.ok?'ok':'error')}catch(e){$('health').textContent='● OFFLINE'}try{await loadModelPool()}catch(e){}try{const d=await(await api('/diagnostics')).json(); $('health').title=Object.entries(d.checks||{}).map(([k,v])=>k+': '+(v?'READY':'MISSING')).join('\n')}catch(e){}try{const ss=await(await api('/sessions')).json();$('sessions').innerHTML=ss.slice(-8).reverse().map(s=>'<div title="'+s.id+'">'+s.task+'</div>').join('')}catch(e){}}
async function loadFiles(){try{const x=await(await api('/workspace/files')).json();$('files').innerHTML=x.files.map(f=>'<div class="file" data-path="'+encodeURIComponent(f)+'">'+f+'</div>').join('');document.querySelectorAll('.file').forEach(el=>el.onclick=()=>openFile(decodeURIComponent(el.dataset.path)))}catch(e){$('files').textContent='Workspace unavailable'}}
async function openFile(path){try{const x=await(await api('/workspace/file?path='+encodeURIComponent(path))).json();$('filename').textContent=x.path;$('filecontent').value=x.content}catch(e){$('filecontent').value='Unable to read file'}}
async function loadGit(){try{$('git').textContent=(await(await api('/workspace/status')).json()).stdout||'Clean working tree'}catch(e){$('git').textContent='Workspace unavailable'}}
async function loadDiff(){try{$('diff').textContent=(await(await api('/workspace/diff')).json()).diff||'No changes'}catch(e){$('diff').textContent='Workspace unavailable'}}
async function decide(allow){if(!currentSession)return;await api('/approvals/'+currentSession,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({allow})});$('approval').classList.add('hidden')}
async function start(){const t=$('task').value.trim();if(!t)return;timeline.innerHTML='';$('runstatus').textContent='RUNNING';try{const r=await api('/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task:t,mode:$('mode').value,max_iterations:30,profile:$('profile').value})});const x=await r.json();if(!r.ok)throw Error(x.detail||'run failed');currentSession=x.session_id;currentJob=x.job_id;connect(x.session_id);pollJob()}catch(e){add('ERROR',e.message);$('runstatus').textContent='FAILED'}}
$('task').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')start()});
load();loadFiles();loadGit();loadDiff();

async function pollJob(){if(!currentJob)return;try{const x=await(await api('/jobs/'+currentJob)).json();$('runstatus').textContent=(x.status||'unknown').toUpperCase();if(['queued','running','waiting'].includes(x.status)){setTimeout(pollJob,1000)}}catch(e){}}
async function cancelJob(){if(currentJob)await api('/jobs/'+currentJob+'/cancel',{method:'POST'});}

function openSetup(){$('setupModal').classList.remove('hidden');runDiagnostics()}
function closeSetup(){$('setupModal').classList.add('hidden')}
async function runDiagnostics(){const el=$('setupChecks');el.textContent='Checking…';try{const d=await(await api('/diagnostics')).json();el.innerHTML=Object.entries(d.checks||{}).map(([k,v])=>'<div class="setup-row"><b>'+k+'</b><span class="'+(v?'ok':'error')+'">'+(v?'READY':'CONFIGURE')+'</span></div>').join('')+(d.ok?'<p class="ok">Core runtime ready.</p>':'<p class="error">Claude Code, workspace or persistence is not ready.</p>')}catch(e){el.textContent='Authentication required or server unavailable.'}}

async function loadModelPool(){const ms=await(await api('/model-pool')).json();$('models').innerHTML=ms.map(m=>'<div class="model"><span>'+m.provider+'/'+m.model+' <small>'+m.roles.join(', ')+'</small></span><span><button class="mini" onclick="testModel(\''+encodeURIComponent(m.provider)+'\',\''+encodeURIComponent(m.model)+'\')">Test</button> <b class="'+(m.free?'free':'')+'">'+(m.available?'READY':'CONFIG')+'</b></span></div>').join('')}
async function refreshModels(){await api('/model-pool/refresh',{method:'POST'});loadModelPool()}
async function testModel(p,m){const x=await(await api('/model-pool/test/'+p+'/'+m,{method:'POST'})).json();add('MODEL',x.provider+'/'+x.model+': '+(x.available?'READY':'UNAVAILABLE'))}

async function renderModelManager(){const ms=await(await api('/model-pool')).json();const el=$('modelManager');el.innerHTML=ms.map((m,i)=>{const s=m.stats||{};return '<div class="model-card '+(m.available?'':'disabled')+'"><div class="model-meta"><b>'+m.provider+'/'+m.model+'</b><span>'+(m.free?'FREE ':'')+(m.available?'READY':'CONFIG')+'</span></div><small>'+m.roles.join(' · ')+'</small><div class="model-stats">Success '+((s.success_rate||0)*100).toFixed(1)+'% · Latency '+(s.latency||0).toFixed(1)+'s · Failures '+(s.fail||0)+' · Score '+(m.score??'—')+'</div><div class="model-actions"><label>Priority <input id="pri'+i+'" type="number" value="'+m.priority+'"></label><button class="mini" onclick="saveModel('+i+')">Save</button><button class="mini" onclick="testModel(\''+encodeURIComponent(m.provider)+'\',\''+encodeURIComponent(m.model)+'\')">Test</button></div></div>'}).join('')};
async function saveModel(i){const ms=await(await api('/model-pool')).json();const m=ms[i];const priority=Number($('pri'+i).value);await api('/model-pool/'+encodeURIComponent(m.provider)+'/'+encodeURIComponent(m.model),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({priority})});await renderModelManager();loadModelPool()}

async function discoverModels(){const x=await(await api('/model-pool/discover',{method:'POST'})).json();add('DISCOVERY','OpenRouter: added '+(x.added||0)+' models');await renderModelManager();await loadModelPool()}

async function loadLearning(){try{const rows=await(await api('/learning')).json();$('learning').innerHTML=rows.length?rows.map(r=>'<div class="model-row"><b>'+r.model+'</b> · '+r.role+' · '+(r.success_rate*100).toFixed(1)+'% · '+r.latency.toFixed(1)+'s · '+r.tasks+' tasks</div>').join(''):'No task history yet.'}catch(e){$('learning').textContent='Unavailable'}}

async function loadTaskGraph(sid){try{const x=await(await api('/task-graph/'+encodeURIComponent(sid))).json();const e=x.events||[];const g=e.length?e[e.length-1].message||e[e.length-1].data:e;const arr=Array.isArray(g)?g:[];$('taskGraph').innerHTML=arr.map(n=>'<div class="model-row"><b>'+n.id+'</b> · '+n.title+' · '+n.status+'</div>').join('')||'No graph data'}catch(e){$('taskGraph').textContent='Unavailable'}}
